//5
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("2.2.0.5")]
[assembly: AssemblyVersion("2.2.0.0")]

namespace ScrapYard
{
	public static class Version
	{
		public const int major = 2;
		public const int minor = 2;
		public const int patch = 0;
		public const int build = 0;
		public const string Number = "2.2.0.0";
#if DEBUG
		public const string Text = Number + " DEBUG";
#else
		public const string Text = Number + "";
#endif
	}
}